name: dockm8
channels:
  - conda-forge
  - schrodinger
  - bioconda
  - mx
  - defaults
dependencies:
  - python=3.10.14
  - rdkit=2023.09
  - spyrmsd
  - kneed
  - molvs
  - xgboost
  - openbabel
  - docopt
  - pdbfixer
  - smina
  - lightning
  - ipykernel
  - scipy
  - seaborn
  - tqdm
  - pytest
  - pydantic
  - reduct
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch==2.2.0
    - torchvision
    - torchaudio
    - pymesh
    - espsim
    - oddt
    - biopandas
    - redo
    - MDAnalysis==2.0.0
    - prody==2.1.0
    - dgl
    - Pebble
    - tensorflow
    - meeko
    - posebusters
    - streamlit
    - prolif
    - datamol
    - yapf
    - medchem
    - molgrid
    - torch_scatter
    - torch_sparse
    - torch_spline_conv
    - torch_cluster
    - torch_geometric
    - streamlit_molstar
    - sh
    - scikit-learn
    - roma
    - pytorch_lightning
    - omegaconf
    - terrace
    - dgllife
    - scikit-learn-extra