name: dockm8
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - tqdm
  - biopandas
  - redo
  - oddt
  - pebble
  - MDAnalysis
  - rdkit
  - chembl_structure_pipeline
  - ipykernel
  - scipy
  - spyrmsd
  - kneed
  - scikit-learn-extra
  - cairosvg
  - svgutils
  - molvs
  - jupyter
  - notebook
  - seaborn
  - xgboost
  - ca-certificates
  - openssl
  - openbabel
  - certifi
  - pip
  - pip:
    - pathlib
    - meeko
    - chembl_webresource_client 
    - molvs
    - git+https://github.com/mayrf/pkasolver.git
    - dgl
    - espsim
    - torch @ https://download.pytorch.org/whl/cpu
    - torchvision @ https://download.pytorch.org/whl/cpu
    - torchaudio @ https://download.pytorch.org/whl/cpu
    - torch_geometric
    - torch_sparse
    - torch_scatter
    - torch_spline_conv
    - posebusters
    - prody
