channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - pytorch
  - cudatoolkit
  - torchvision
  - torchaudio
  - python
  - tqdm
  - biopandas
  - redo
  - oddt
  - pebble
  - MDAnalysis
  - rdkit
  - chembl_structure_pipeline
  - ipykernel
  - scipy
  - spyrmsd
  - kneed
  - scikit-learn-extra
  - cairosvg
  - svgutils
  - molvs
  - jupyter
  - notebook
  - seaborn
  - xgboost
  - ca-certificates
  - openssl
  - openbabel
  - certifi
  - pip
  - pip:
    - pathlib
    - meeko
    - torch-sparse
    - torch-scatter
    - chembl_webresource_client 
    - molvs
    - git+https://github.com/mayrf/pkasolver.git
    - dgl
    - espsim
    - torch-geometric
