   package:
     name: dockm8
     version: 1.0.0

   source:
     git-url: https://gitlab.com/Tonylac77/DockM8.git

   requirements:
     build:
       - python
       - setuptools
     run:
       - python

   about:
    home: https://gitlab.com/Tonylac77/DockM8
