[tool.pytest.ini_options]
# Directories to look for tests.
testpaths = ["tests", "integration"]

# Additional command line options for pytest.
addopts = "-v -ra -q"

# Enable logging to the console.
log_cli = true

# Set the logging level for console output.
log_cli_level = "INFO"

# Format for log messages.
log_format = "%(asctime)s %(levelname)s %(message)s"

# Date format for log messages.
log_date_format = "%Y-%m-%d %H:%M:%S"

# Minimum pytest version required.
minversion = "6.0"

# Warnings to ignore during tests.
filterwarnings = "ignore"

# Custom directory for pytest cache.
cache_dir = ".pytest_cache"

# ignore certain Directories
norecursedirs = ["software", "tests/test_files/setup"]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
ignore = ["E402"]

[tool.yapf]
# Base style for yapf formatting.
based_on_style = "google"
split_before_closing_bracket = false
arithmetic_precedence_indication = true
blank_lines_around_top_level_definition = 2
blank_line_before_class_docstring = 1
blank_line_before_module_docstring = 0
blank_line_before_nested_class_or_def = 1
align_closing_bracket_with_visual_indent = false
continuation_align_style = "VALIGN-RIGHT"
each_dict_entry_on_separate_line = true
dedent_closing_brackets = false
column_limit = 120
indent_dictionary_value = true
indent_width = 4
indent_blank_lines = false
join_multiple_lines = true
space_between_ending_comma_and_closing_bracket = true
split_all_top_level_comma_separated_values = true
split_before_bitwise_operator = false
split_before_dict_set_generator = false
split_before_logical_operator = false
split_before_arithmetic_operator = false
split_before_dot = false
spaces_before_comment = "10, 30, 50, 70"
split_complex_comprehension = true
split_penalty_comprehension = 2100
use_tabs = true
disable_ending_comma_heuristic = true