[tool.pytest.ini_options]
# Directories to look for tests.
testpaths = ["tests", "integration"]

# Additional command line options for pytest.
addopts = "-v -ra -q"

# Enable logging to the console.
log_cli = true

# Set the logging level for console output.
log_cli_level = "INFO"

# Format for log messages.
log_format = "%(asctime)s %(levelname)s %(message)s"

# Date format for log messages.
log_date_format = "%Y-%m-%d %H:%M:%S"

# Minimum pytest version required.
minversion = "6.0"

# Warnings to ignore during tests.
filterwarnings = "ignore"

# Custom directory for pytest cache.
cache_dir = ".pytest_cache"

[tool.yapf]
# Base style for yapf formatting.
based_on_style = "google"
split_before_closing_bracket = false
ARITHMETIC_PRECEDENCE_INDICATION = true
BLANK_LINES_AROUND_TOP_LEVEL_DEFINITION = 2
BLANK_LINE_BEFORE_CLASS_DOCSTRING = 1
BLANK_LINE_BEFORE_MODULE_DOCSTRING = 0
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = 1
ALIGN_CLOSING_BRACKET_WITH_VISUAL_INDENT = false
CONTINUATION_ALIGN_STYLE = "VALIGN-RIGHT"
EACH_DICT_ENTRY_ON_SEPARATE_LINE = true
DEDENT_CLOSING_BRACKETS = false
COLUMN_LIMIT = 120
INDENT_DICTIONARY_VALUE = true
INDENT_WIDTH = 4
INDENT_BLANK_LINES = false
JOIN_MULTIPLE_LINES = true
SPACE_BETWEEN_ENDING_COMMA_AND_CLOSING_BRACKET = true
SPLIT_ALL_TOP_LEVEL_COMMA_SEPARATED_VALUES = true
SPLIT_BEFORE_BITWISE_OPERATOR = false
SPLIT_BEFORE_DICT_SET_GENERATOR = false
SPLIT_BEFORE_LOGICAL_OPERATOR = false
SPLIT_BEFORE_ARITHMETIC_OPERATOR = false
SPLIT_BEFORE_DOT = false
SPACES_BEFORE_COMMENT = "10, 30, 50, 70"
SPLIT_COMPLEX_COMPREHENSION = true
SPLIT_PENALTY_COMPREHENSION = 2100
USE_TABS = true
DISABLE_ENDING_COMMA_HEURISTIC = true